services:
  cdk-duihuan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cdk-duihuan
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env
    environment:
      APP_PORT: 5090
