services:
  cdk-duihuan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cdk-duihuan
    restart: unless-stopped
    env_file:
      - .env
    environment:
      APP_PORT: 5090
    ports:
      - "5090:5090"
